services:
  accra:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker_compose.env
    environment:
      ACCRA_TIMEOUT: 1000
    ports:
      - "127.0.0.1:8888:8888" # Jupyter-lab
    stdin_open: true
    tty: true
    volumes:
      - .:/app # TODO: remove for production
    command: "/bin/bash"
